#!/usr/bin/env node
/**
 * FutureDev app icons — geometric craft, not a bubbly placeholder F.
 *
 * Mark: four ascending bars (learning / career progress) on accent.
 * Token colors from @futuredev/design-tokens. Regenerates icon.png,
 * adaptive-icon.png, splash.png, and Android mipmap WEBPs.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';
import { colors } from '@futuredev/design-tokens';
import { syncAndroidMipmaps, verifyForegroundBars } from './sync-android-icons.mjs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const assetsDir = join(__dirname, '..', 'assets');
mkdirSync(assetsDir, { recursive: true });

const accent = colors.light.accent;
const onAccent = colors.light.accentText;
const pageBg = colors.light.bg;

/**
 * Ascending ladder mark — reads at 48px, distinct from Facebook-F candy icons.
 * Bars grow left→right length; equal thickness; tight optical stack.
 */
function markSvg(size, { background, foreground, transparentBg = false }) {
  const pad = size * 0.22;
  const gap = size * 0.045;
  const barH = size * 0.095;
  const rx = barH * 0.28;
  const stackH = 4 * barH + 3 * gap;
  const top0 = (size - stackH) / 2;
  const fracs = [0.42, 0.58, 0.74, 0.9];
  const maxW = size - pad * 2;

  const bars = fracs
    .map((frac, i) => {
      const w = maxW * frac;
      const x = (size - w) / 2;
      const y = top0 + i * (barH + gap);
      return `<rect x="${x.toFixed(2)}" y="${y.toFixed(2)}" width="${w.toFixed(2)}" height="${barH.toFixed(2)}" rx="${rx.toFixed(2)}" fill="${foreground}" />`;
    })
    .join('\n  ');

  const bgRect = transparentBg
    ? ''
    : `<rect width="${size}" height="${size}" fill="${background}" />`;

  return `<svg width="${size}" height="${size}" viewBox="0 0 ${size} ${size}" xmlns="http://www.w3.org/2000/svg">
  ${bgRect}
  ${bars}
</svg>`;
}

async function renderPng(svg, size, outPath) {
  await sharp(Buffer.from(svg)).resize(size, size).png().toFile(outPath);
  console.log(`make-icons: ${outPath} (${size}x${size})`);
}

async function main() {
  const fullMarkSvg = markSvg(1024, { background: accent, foreground: onAccent });

  await renderPng(fullMarkSvg, 1024, join(assetsDir, 'icon.png'));
  await renderPng(fullMarkSvg, 1024, join(assetsDir, 'adaptive-icon.png'));

  const splashSize = 1284;
  const motifSize = 440;
  const motifSvg = markSvg(motifSize, { background: accent, foreground: onAccent });
  const motifPng = await sharp(Buffer.from(motifSvg))
    .resize(motifSize, motifSize)
    .png()
    .toBuffer();

  const radius = Math.round(motifSize * 0.22);
  const rounded = Buffer.from(
    `<svg width="${motifSize}" height="${motifSize}"><rect width="${motifSize}" height="${motifSize}" rx="${radius}" fill="#fff"/></svg>`,
  );
  const motifRounded = await sharp(motifPng)
    .composite([{ input: await sharp(rounded).png().toBuffer(), blend: 'dest-in' }])
    .png()
    .toBuffer();

  await sharp({
    create: {
      width: splashSize,
      height: splashSize,
      channels: 4,
      background: pageBg,
    },
  })
    .composite([{ input: motifRounded, gravity: 'center' }])
    .png()
    .toFile(join(assetsDir, 'splash.png'));
  console.log(`make-icons: ${join(assetsDir, 'splash.png')} (${splashSize}x${splashSize})`);

  writeFileSync(
    join(assetsDir, 'README.md'),
    [
      '# App icons',
      '',
      'Generated by `scripts/make-icons.mjs` from a geometric **ascending-bar** mark',
      `(learning / career progress) in design-token accent \`#2A5FD9\` — not a stock`,
      'image and not a bubbly single-letter F.',
      '',
      'Also syncs Android `res/mipmap-*/ic_launcher*.webp` (required for the launcher;',
      'Expo `assets/` alone do not update a committed `android/` tree).',
      '',
      'Regenerate: `pnpm --filter @futuredev/mobile make-icons`',
      '',
      'Android mipmaps only: `pnpm --filter @futuredev/mobile sync-android-icons`',
      '',
    ].join('\n'),
  );

  await syncAndroidMipmaps();
  const { runs, sampleWidths } = await verifyForegroundBars();
  console.log(
    `verify xxxhdpi foreground: center-column white runs=${runs}, bar widths=${sampleWidths.join(', ')}`,
  );
  if (runs !== 4) {
    throw new Error(`Expected 4 ascending bar bands on center column, got ${runs}`);
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
